#!/bin/bash

set -e
set -x

docker-compose down

function build() {
  ./gradlew assemble

  docker-compose build
}

function push() {
  docker push jimbrighter/photodump-frontend
  docker push jimbrighter/photodump-backend
}

if [ "$1" == "clean" ]; then
    set +e
    ./gradlew clean
    docker-compose down
    docker rm $(docker ps -a -f status=exited | awk "{print \$1}")
    docker rmi $(docker images | grep "<none>" | awk "{print \$3}")
    docker volume rm $(docker volume ls | awk "{print \$2}")
    docker network rm $(docker network ls | grep "photodump" | awk "{print \$1}")

elif [ "$1" == "build" ]; then
    build

elif [ "$1" == "push" ]; then
    build
    push

else
    build
    docker-compose up
fi
