#!/bin/bash

set -e
set -x

function build() {
  ./gradlew assemble

  docker-compose build
}

function push() {
  docker-compose push
}

if [ "$1" == "clean" ]; then
    set +e
    docker-compose down -v --remove-orphans

elif [ "$1" == "build" ]; then
    build

elif [ "$1" == "push" ]; then
    build
    push

elif [ "$1" == "silent" ]; then
    build
    docker-compose up -d

else
    build
    docker-compose up
fi
