version: '2'
services:
  app-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: jimbrighter/photodump-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      - db-service
    networks:
      backend:
        aliases:
          - app
    environment:
      - DB_USER=postgres
      - DB_PASS=pass
      - DB_URL=jdbc:postgresql://db/imagedb
      - SPRING_PROFILES=local

  front-service:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: jimbrighter/photodump-frontend:latest
    ports:
      - "9001:9001"
    networks:
      backend:
        aliases:
          - front

  db-service:
    build:
      context: ./db
      dockerfile: dockerfile-db
    image: jimbrighter/photodump-db:latest
    ports:
      - "5454:5432"
    networks:
      backend:
        aliases:
          - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pass

networks:
  backend:
