version: '2'
networks:
  photodump:
services:
  app-service:
    container_name: photodump
    image: jimbrighter/photodump-backend:latest
    ports:
      - "8080:8080"
    mem_limit: 512m
    restart: always
    depends_on:
      - db-service
    networks:
      photodump:
        aliases:
          - app
    env_file: secrets.env

  front-service:
    container_name: photodump-front
    image: jimbrighter/photodump-frontend:latest
    ports:
      - "80:9001"
    mem_limit: 50m
    restart: always
    networks:
      photodump:
        aliases:
          - front

  db-service:
    container_name: photodump-db
    image: jimbrighter/photodump-db:latest
    ports:
      - "5432:5432"
    mem_limit: 50m
    restart: always
    networks:
      photodump:
        aliases:
          - db
    volumes:
      - /home/jbrighter/postgres:/var/lib/postgresql/data
    env_file: secrets.env
